development:
  adapter: postgresql
  encoding: unicode
  database: wcsf_development
  host: localhost
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: wcsf_test
  host: localhost
  pool: 5
